micronaut:
  application:
    name: trade-service

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/trade-service
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    schema-generate: NONE # Flyway handles DDL
    dialect: POSTGRES

flyway:
 datasources:
  default:
   enabled: true
   locations: classpath:db/migration
   baseline-on-migrate: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

kafka:
 bootstrap:
  servers: localhost:9092
 producers:
  default:
   acks: all
   retries: 3
   enable-idempotence: true

app:
 outbox:
  poll-interval: 5s
  initial-delay: 10s
 kafka:
  topics:
   trades: trades-events
