<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.miaoubich.ledger</groupId>
	<artifactId>ledger-service</artifactId>
	<version>0.1</version>
	<packaging>jar</packaging>

	<parent>
		<groupId>io.micronaut.platform</groupId>
		<artifactId>micronaut-parent</artifactId>
		<version>4.10.17</version>
	</parent>

	<properties>
		<jdk.version>25</jdk.version>
		<release.version>25</release.version>
		<micronaut.version>4.10.17</micronaut.version>
		<micronaut.aot.enabled>false</micronaut.aot.enabled>
		<micronaut.aot.packageName>com.miaoubich.aot.generated</micronaut.aot.packageName>
		<micronaut.runtime>netty</micronaut.runtime>
		<exec.mainClass>com.miaoubich.ledger.LadgerApplication</exec.mainClass>
		<hibernate.version>6.6.49.Final</hibernate.version>
	</properties>

	<repositories>
		<repository>
			<id>central</id>
			<url>https://repo.maven.apache.org/maven2</url>
		</repository>
	</repositories>

	<dependencies>
		<!-- Micronaut Core & Serialization -->
		<dependency>
			<groupId>io.micronaut</groupId>
			<artifactId>micronaut-runtime</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.micronaut.serde</groupId>
			<artifactId>micronaut-serde-jackson</artifactId>
			<scope>compile</scope>
		</dependency>

		<!-- netty server -->
		<dependency>
			<groupId>io.micronaut</groupId>
			<artifactId>micronaut-http-server-netty</artifactId>
			<scope>compile</scope>
		</dependency>
		
		<!-- Kafka Consumer -->
		<dependency>
			<groupId>io.micronaut.kafka</groupId>
			<artifactId>micronaut-kafka</artifactId>
			<scope>compile</scope>
		</dependency>

		<!-- Data JPA & Postgres Driver -->
		<dependency>
			<groupId>io.micronaut.data</groupId>
			<artifactId>micronaut-data-hibernate-jpa</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.micronaut.sql</groupId>
			<artifactId>micronaut-jdbc-hikari</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!-- Required for application.yml parsing (Micronaut 4.7+) -->
		<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!-- Slf4j -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<scope>runtime</scope>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>io.micronaut.maven</groupId>
				<artifactId>micronaut-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<!-- Annotation Processors -->
					<annotationProcessorPaths combine.children="append">
						<path>
							<groupId>io.micronaut</groupId>
							<artifactId>micronaut-inject-java</artifactId>
							<version>${micronaut.core.version}</version>
						</path>
						<path>
							<groupId>io.micronaut.data</groupId>
							<artifactId>micronaut-data-processor</artifactId>
							<version>${micronaut.data.version}</version>
						</path>
<!--						<path>-->
<!--							<groupId>io.micronaut.data</groupId>-->
<!--							<artifactId>micronaut-data-hibernate-jpa</artifactId>-->
<!--							<version>${micronaut.data.version}</version>-->
<!--						</path>-->
						<path>
							<groupId>io.micronaut.serde</groupId>
							<artifactId>micronaut-serde-processor</artifactId>
							<version>${micronaut.serialization.version}</version>
						</path>
					</annotationProcessorPaths>
					<compilerArgs>
						<arg>-Amicronaut.processing.group=com.miaoubich</arg>
						<arg>-Amicronaut.processing.module=ledger-service</arg>
					</compilerArgs>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>